name: Build

on:
  workflow_dispatch:
    inputs:
      build_variant:
        description: 'Build variant to test'
        default: 'treble_arm64_bgN'
        required: false
        type: string
  # push:
  #   branches:
  #     - android-15.0
  #   paths-ignore:
  #     - '.github/**'
  #     - 'config/**'

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Build Variant
        run: echo "BUILD_VARIANT=${{ inputs.build_variant || 'treble_arm64_bgN' }}" >> $GITHUB_ENV

      - name: Build Image
        run: docker build -f build/Dockerfile -t ponces/treble .

      - name: Build ROM
        run: |
          mkdir builds
          docker run --rm \
                     --privileged \
                     --name test \
                     --volume /root/.ssh:/root/.ssh \
                     --volume ${{ github.workspace }}/builds:/root/builds \
                     ponces/treble treblebuild ${{ env.BUILD_VARIANT }}

      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_VARIANT }}
          path: builds/*.xz
